const express = require('express');
const cors = require('cors');
require('dotenv').config();
const app = express();
const PORT = process.env.PORT || 3000;
app.use(cors({ origin: ['http://localhost:5173', 'http://127.0.0.1:5173'] }));
app.use(express.json());
app.use('/api', require('./routes/authRoutes'));
app.use('/api', require('./routes/accessRoutes'));
app.use('/api/productos', require('./routes/productRoutes'));
app.use('/api', require('./routes/contentRoutes'));
app.use('/api', require('./routes/checkoutRoutes'));
app.use('/api/datos_tarjeta', require('./routes/tarjetasRoutes'));
app.use('/api/usuarios', require('./routes/userRoutes'));
app.use('/api', require('./routes/checkoutTarjetaRoutes'));
app.use('/api/pedidos', require('./routes/pedidoRoutes'));
app.use('/api/ingresos', require('./routes/ingresosRoutes'));
app.use('/api/resenas', require('./routes/resenaRoutes'));
app.use('/api/pedidos', require('./routes/pedidosAdminRoutes'));
app.get('/', (req, res) => res.send('Servidor Node.js corriendo'));
if (require.main === module) app.listen(PORT, '0.0.0.0', () => {
  console.log(`Servidor corriendo en http://0.0.0.0:${PORT}`);
});
module.exports = app;
