-- Migracion: roles, permisos y auditoria.
BEGIN;

-- Evita cambios concurrentes en usuarios durante la migracion.
LOCK TABLE public.usuario IN ACCESS EXCLUSIVE MODE;

CREATE TABLE public.roles (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(100) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    es_sistema BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT roles_codigo_valido CHECK (
        codigo = lower(btrim(codigo)) AND codigo <> ''
    ),
    CONSTRAINT roles_nombre_valido CHECK (btrim(nombre) <> '')
);

CREATE TABLE public.permisos (
    id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT NOT NULL,
    CONSTRAINT permisos_codigo_valido CHECK (
        codigo = lower(btrim(codigo)) AND codigo <> ''
    )
);

CREATE TABLE public.rol_permiso (
    id_rol INTEGER NOT NULL,
    id_permiso INTEGER NOT NULL,
    PRIMARY KEY (id_rol, id_permiso),
    CONSTRAINT fk_rol_permiso_rol FOREIGN KEY (id_rol)
        REFERENCES public.roles (id_rol) ON DELETE CASCADE,
    CONSTRAINT fk_rol_permiso_permiso FOREIGN KEY (id_permiso)
        REFERENCES public.permisos (id_permiso) ON DELETE CASCADE
);

CREATE INDEX idx_rol_permiso_permiso ON public.rol_permiso (id_permiso);

CREATE TABLE public.auditoria (
    id_auditoria BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER,
    actor_referencia TEXT NOT NULL,
    accion VARCHAR(100) NOT NULL,
    entidad VARCHAR(100) NOT NULL,
    id_entidad TEXT,
    fecha TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    detalle JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (id_usuario)
        REFERENCES public.usuario (id_usuario) ON DELETE SET NULL,
    CONSTRAINT auditoria_actor_valido CHECK (btrim(actor_referencia) <> ''),
    CONSTRAINT auditoria_accion_valida CHECK (btrim(accion) <> ''),
    CONSTRAINT auditoria_entidad_valida CHECK (btrim(entidad) <> '')
);

CREATE INDEX idx_auditoria_fecha ON public.auditoria (fecha DESC);
CREATE INDEX idx_auditoria_usuario_fecha
    ON public.auditoria (id_usuario, fecha DESC);

-- IDs iniciales conocidos. El codigo identifica el significado del rol.
INSERT INTO public.roles (id_rol, codigo, nombre, descripcion, es_sistema)
VALUES
    (1, 'cliente', 'Cliente', 'Acceso a las funciones de cliente.', TRUE),
    (2, 'admin', 'Administrador', 'Administracion de contenido, usuarios, roles y configuracion.', TRUE),
    (3, 'editor', 'Editor', 'Crea, edita y elimina productos y categorias.', TRUE);

-- Ajusta la secuencia tras insertar IDs explicitos.
SELECT setval(
    pg_get_serial_sequence('public.roles', 'id_rol'),
    (SELECT MAX(id_rol) FROM public.roles),
    TRUE
);

INSERT INTO public.permisos (codigo, descripcion) VALUES
    ('productos.ver', 'Consultar productos.'),
    ('productos.crear', 'Crear productos.'),
    ('productos.editar', 'Editar productos.'),
    ('productos.eliminar', 'Eliminar productos.'),
    ('categorias.ver', 'Consultar categorias.'),
    ('categorias.crear', 'Crear categorias.'),
    ('categorias.editar', 'Editar categorias.'),
    ('categorias.eliminar', 'Eliminar categorias.'),
    ('usuarios.ver', 'Consultar usuarios.'),
    ('usuarios.crear', 'Crear usuarios desde administracion.'),
    ('usuarios.editar', 'Editar usuarios desde administracion.'),
    ('usuarios.eliminar', 'Eliminar usuarios desde administracion.'),
    ('roles.ver', 'Consultar roles y permisos disponibles.'),
    ('roles.crear', 'Crear roles personalizados.'),
    ('roles.editar', 'Editar roles y sus permisos.'),
    ('roles.eliminar', 'Eliminar roles personalizados sin usuarios asignados.'),
    ('roles.asignar', 'Asignar un rol a un usuario.'),
    ('roles.revocar', 'Revocar un rol sustituyendolo por Cliente.'),
    ('configuracion.editar', 'Modificar configuraciones globales.'),
    ('auditoria.ver', 'Consultar el registro de auditoria.'),
    ('pedidos.gestionar', 'Consultar y gestionar pedidos desde administracion.'),
    ('ingresos.ver', 'Consultar ingresos desde administracion.');

-- Administrador recibe todos los permisos definidos en esta migracion.
INSERT INTO public.rol_permiso (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM public.roles r CROSS JOIN public.permisos p
WHERE r.codigo = 'admin';

-- Editor: exclusivamente contenido (productos y categorias).
INSERT INTO public.rol_permiso (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM public.roles r CROSS JOIN public.permisos p
WHERE r.codigo = 'editor' AND p.codigo IN (
    'productos.ver', 'productos.crear', 'productos.editar', 'productos.eliminar',
    'categorias.ver', 'categorias.crear', 'categorias.editar', 'categorias.eliminar'
);

INSERT INTO public.rol_permiso (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM public.roles r CROSS JOIN public.permisos p
WHERE r.codigo = 'cliente'
  AND p.codigo IN ('productos.ver', 'categorias.ver');

-- Preserva otros roles existentes sin conceder permisos automaticamente.
-- Normaliza espacios, mayusculas y el alias administrador -> admin.
INSERT INTO public.roles (codigo, nombre, descripcion)
SELECT DISTINCT
    lower(btrim(u.rol)), lower(btrim(u.rol)),
    'Rol migrado; revisar y asignar permisos antes de utilizarlo.'
FROM public.usuario u
WHERE NULLIF(btrim(u.rol), '') IS NOT NULL
  AND lower(btrim(u.rol)) NOT IN ('cliente', 'admin', 'administrador', 'editor');

ALTER TABLE public.usuario ADD COLUMN id_rol INTEGER;

UPDATE public.usuario u
SET id_rol = r.id_rol
FROM public.roles r
WHERE r.codigo = CASE
    WHEN NULLIF(btrim(u.rol), '') IS NULL THEN 'cliente'
    WHEN lower(btrim(u.rol)) = 'administrador' THEN 'admin'
    ELSE lower(btrim(u.rol))
END;

-- Si algun usuario no se pudo migrar, NOT NULL falla y se revierte la transaccion.
ALTER TABLE public.usuario
    ALTER COLUMN id_rol SET NOT NULL,
    ALTER COLUMN id_rol SET DEFAULT 1,
    ADD CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol)
        REFERENCES public.roles (id_rol) ON DELETE RESTRICT;

CREATE INDEX idx_usuario_id_rol ON public.usuario (id_rol);

COMMENT ON COLUMN public.usuario.rol IS
    'Columna heredada. Migrar el backend a id_rol y despues retirar esta columna.';
COMMENT ON COLUMN public.auditoria.actor_referencia IS
    'Referencia estable del actor, por ejemplo usuario:42; se conserva al eliminarlo.';
COMMENT ON COLUMN public.auditoria.detalle IS
    'Metadatos de la accion; no almacenar contrasenas ni datos sensibles de pago.';

COMMIT;

ALTER TABLE public.usuario DROP COLUMN rol;



